### PR TITLE
fix: loading indicator not working for some forms

### LINKED ISSUE #80: Loading state are not working for `/onboarding` and stakeholder invite buttons
Steps to reproduce

### Onboarding page
* Start the server and signup
* It'll take you to `/onboarding` page
* Complete the form and submit
* The loading state does not work as expected.

### Stakeholder invite
* After you are redirected to dashboard, go to `/stakeholder` page
* Click on `+ Stakeholder` button
* Complete the form and submit
* The loading state does not work as expected.

You can find login/signup pages as reference on how its supposed to work.

### PR DESCRIPTION
**Pull request by G3root**
fixes #80

[Screencast 2024-01-29 13:55:17.webm](https://github.com/opencapco/opencap.co/assets/84864519/c347a24d-5a1c-4bb2-a1b8-0dc186bb2d46)

### CODE REVIEW

File: src/components/stakeholder/member-modal.tsx [hunk 1]
```diff
@@ -119,7 +124,10 @@ const MemberModal = ({
       trigger={children}
       dialogProps={{
         open,
-        onOpenChange: setOpen,
+        onOpenChange: (val) => {
+          setOpen(val);
+          form.reset();
```
Comment (G3root) [inline src/components/stakeholder/member-modal.tsx:129]: rest form on exit

**Review by dahal — APPROVED** [review]
🚀
